export const rawData = {
  titles: [
    {
      availability: { isPlayable: true, unplayableCause: null },
      inRemindMeList: false,
      queue: { available: true, inQueue: false },
      summary: {
        type: "movie",
        unifiedEntityId: "Video:70267266",
        id: 70267266,
        isOriginal: false,
        liveEvent: { hasLiveEvent: false },
      },
      jawSummary: {
        trackIds: {
          videoId: 70267266,
          trackId_jaw: 14277281,
          trackId_jawEpisode: 14277283,
          trackId_jawTrailer: 14277282,
          trackId: 14277281,
        },
        tags: [
          { id: 100033, name: "Cerebral" },
          { id: 100047, name: "Inspiring" },
        ],
        cast: [
          { id: 20017210, name: "Ashton Kutcher" },
          { id: 20007490, name: "Dermot Mulroney" },
          { id: 30073464, name: "Josh Gad" },
          { id: 38073, name: "Lukas Haas" },
          { id: 20028161, name: "J.K. Simmons" },
          { id: 97408, name: "Lesley Ann Warren" },
          { id: 27458, name: "Ron Eldard" },
          { id: 30142687, name: "Ahna O'Reilly" },
          { id: 20041635, name: "Victor Rasuk" },
          { id: 20009878, name: "John Getz" },
          { id: 100763, name: "James Woods" },
          { id: 64636, name: "Matthew Modine" },
        ],
        creators: [],
        directors: [{ id: 30037552, name: "Joshua Michael Stern" }],
        writers: [{ id: 60174746, name: "Matt Whiteley" }],
        genres: [
          { id: 5763, name: "Drama Movies" },
          { id: 920, name: "Movies Based on Real Life" },
        ],
        availability: { isPlayable: true, unplayableCause: null },
        contextualSynopsis: {
          text: "Silicon Valley genius Steve Jobs changes the world but alienates the people around him as he rises from college dropout to the head of Apple.",
          evidenceKey: "synopsis|70267266-DEFAULT-Informative150--en|en|_UPD_",
        },
        currentContextualSynopsis: {
          text: "Silicon Valley genius Steve Jobs changes the world but alienates the people around him as he rises from college dropout to the head of Apple.",
          evidenceKey: "synopsis|70267266-DEFAULT-Informative150--en|en|_UPD_",
        },
        maturity: {
          rating: {
            value: "PG-13",
            maturityDescription: "some drug content and brief strong language",
            specificRatingReason: "some drug content and brief strong language",
            maturityLevel: 80,
            board: "MPAA",
            boardId: 1,
            ratingId: 124,
            reasons: [],
          },
        },
        unifiedEntityId: "Video:70267266",
        id: 70267266,
        type: "movie",
        isOriginal: false,
        liveEvent: {},
        mostLikedVideoId: 70267266,
        videoId: 70267266,
        requestId: "2a549fd8-0bd0-4388-a413-3a9b19ce9a03-167722651",
        userRatingRequestId: "2a549fd8-0bd0-4388-a413-3a9b19ce9a03-167722651",
        title: "Jobs",
        copyright: null,
        releaseYear: 2013,
        watched: false,
        hasAudioDescription: false,
        synopsis:
          "Silicon Valley genius Steve Jobs changes the world but alienates the people around him as he rises from college dropout to the head of Apple.",
        synopsisRegular:
          "Silicon Valley genius Steve Jobs changes the world but alienates the people around him as he rises from college dropout to the head of Apple.",
        hasSensitiveMetaData: false,
        delivery: {
          has3D: false,
          hasHD: true,
          hasUltraHD: false,
          hasHDR: false,
          hasDolbyVision: false,
          hasDolbyAtmos: false,
          has51Audio: true,
          quality: "HD",
          hasAudioAssistive: false,
          hasTextClosedCaptions: true,
          hasAudioSpatial: false,
        },
        titleMaturity: { level: 80 },
        broadcaster: { broadcasterName: null },
        trailerSummary: { length: 0 },
        supplementalMessageIcon: "REGULAR",
        runtime: 7666,
        videoMerch: {
          unifiedEntityId: "Video:81190582",
          videoId: 70267266,
          id: 81190582,
          start: 0,
          computeId: "browse|81190582|en-TR|_UPD_",
        },
        logoImage: {
          videoId: 70267266,
          url: "https://occ-0-3933-116.1.nflxso.net/dnm/api/v6/beuYL-MTCxPyt5oTOhVnWNGfZug/AAAABWyTsXHyJY1er-y_hRnX2kQn_rrKL15_yZQSh6vUkIWUtTJRb6_b_Xt9xIueJbzAxCH2YaA32s7ay3SAedtFdjQO5lIHu-AAaqgXJQ02ZDo.webp?r=7de",
          type: "LOGO_BRANDED_HORIZONTAL",
          width: 625,
          height: 250,
          extension: "webp",
          size: "_LOGO_BRANDED_HORIZONTAL",
          imageKey:
            "LOGO_BRANDED_HORIZONTAL|e9616290-fc8b-11ec-a596-0e1745432837|en",
        },
        backgroundImage: {
          videoId: 70267266,
          url: "https://occ-0-3933-116.1.nflxso.net/dnm/api/v6/E8vDc_W8CLv7-yMQu8KMEC7Rrr8/AAAABSaKjLCcLrStEyQCYqMXDQzgvPM2ig9urCLIYhFG5QDZfr2p7ZMulz2sfekzIndWagz8LO3JXth5YPd7s9y-l9YbnwFrOt_z4j5J.webp?r=dae",
          width: 848,
          height: 477,
          extension: "webp",
          size: 480,
          focalPoint: '{"x":0.5081,"y":0.2875}',
          imageKey: "StoryArt|ae0d5830-fbc3-11f0-8dde-0affe7238c0d|en",
        },
      },
    },
    {
      availability: { isPlayable: true, unplayableCause: null },
      inRemindMeList: false,
      queue: { available: true, inQueue: false },
      summary: {
        type: "show",
        unifiedEntityId: "Video:80057281",
        id: 80057281,
        isOriginal: true,
        liveEvent: { hasLiveEvent: false },
      },
      episodeCount: 42,
      jawSummary: {
        trackIds: {
          videoId: 80057281,
          trackId_jaw: 14277281,
          trackId_jawEpisode: 14277283,
          trackId_jawTrailer: 14277282,
          trackId: 14277281,
        },
        tags: [
          { id: 108911, name: "Ominous" },
          { id: 104784, name: "Nostalgic" },
          { id: 100053, name: "Scary" },
        ],
        cast: [
          { id: 81117, name: "Winona Ryder" },
          { id: 30074539, name: "David Harbour" },
          { id: 40080328, name: "Millie Bobby Brown" },
          { id: 40080327, name: "Finn Wolfhard" },
          { id: 40080425, name: "Gaten Matarazzo" },
          { id: 40080241, name: "Caleb McLaughlin" },
          { id: 40013337, name: "Noah Schnapp" },
          { id: 40007740, name: "Sadie Sink" },
          { id: 40080329, name: "Natalia Dyer" },
          { id: 40080224, name: "Charlie Heaton" },
          { id: 40084216, name: "Joe Keery" },
          { id: 40197835, name: "Maya Hawke" },
          { id: 30148014, name: "Brett Gelman" },
          { id: 40181927, name: "Priah Ferguson" },
          { id: 40093263, name: "Dacre Montgomery" },
          { id: 12609, name: "Cara Buono" },
          { id: 64636, name: "Matthew Modine" },
          { id: 77279, name: "Paul Reiser" },
          { id: 3553, name: "Sean Astin" },
          { id: 30076875, name: "Jamie Campbell Bower" },
          { id: 38771, name: "Linda Hamilton" },
          { id: 60607930, name: "Nell Fisher" },
          { id: 70612739, name: "Jake Connelly" },
        ],
        creators: [{ id: 40089430, name: "The Duffer Brothers" }],
        directors: [],
        writers: [],
        genres: [
          { id: 11714, name: "TV Dramas" },
          { id: 3300242, name: "Sci-Fi TV" },
          { id: 60951, name: "Teen TV Shows" },
          { id: 83059, name: "TV Horror" },
        ],
        availability: { isPlayable: true, unplayableCause: null },
        contextualSynopsis: {
          text: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
          evidenceKey: "synopsis|80057281-DEFAULT-Narrative--en|en|_UPD_",
        },
        currentContextualSynopsis: {
          text: "On his way home from a friend's house, young Will sees something terrifying. Nearby, a sinister secret lurks in the depths of a government lab.",
          evidenceKey: "web_synopsis|80077368_INFORMATIVE|en",
        },
        maturity: {
          rating: {
            value: "TV-14",
            maturityDescription:
              "Parents strongly cautioned. May not be suitable for ages under 14.",
            specificRatingReason:
              "fear, language, gore, smoking, disturbing images",
            maturityLevel: 90,
            board: "US TV",
            boardId: 10,
            ratingId: 137,
            reasons: [
              { id: 7424, levelDescription: null, reasonDescription: "fear" },
              {
                id: 7426,
                levelDescription: null,
                reasonDescription: "language",
              },
              { id: 7429, levelDescription: null, reasonDescription: "gore" },
              {
                id: 7430,
                levelDescription: null,
                reasonDescription: "smoking",
              },
              {
                id: 7432,
                levelDescription: null,
                reasonDescription: "disturbing images",
              },
            ],
          },
        },
        unifiedEntityId: "Video:80057281",
        id: 80057281,
        type: "show",
        isOriginal: true,
        liveEvent: {},
        mostLikedVideoId: 80057281,
        videoId: 80057281,
        requestId: "2a549fd8-0bd0-4388-a413-3a9b19ce9a03-167722651",
        userRatingRequestId: "2a549fd8-0bd0-4388-a413-3a9b19ce9a03-167722651",
        title: "Stranger Things",
        copyright: null,
        releaseYear: 2025,
        watched: true,
        hasAudioDescription: true,
        synopsis:
          "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
        synopsisRegular:
          "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
        hasSensitiveMetaData: false,
        delivery: {
          has3D: false,
          hasHD: true,
          hasUltraHD: false,
          hasHDR: false,
          hasDolbyVision: false,
          hasDolbyAtmos: false,
          has51Audio: true,
          quality: "HD",
          hasAudioAssistive: true,
          hasTextClosedCaptions: true,
          hasAudioSpatial: false,
        },
        titleMaturity: { level: 90 },
        broadcaster: { broadcasterName: null },
        trailerSummary: { length: 23 },
        supplementalMessageIcon: "REGULAR",
        videoMerch: {
          unifiedEntityId: "Video:82052182",
          videoId: 80057281,
          id: 82052182,
          start: 0,
          computeId: "browse|82052182|en-TR|_UPD_",
        },
        seasonAbbr: "S1",
        seasonCount: 5,
        numSeasonsLabel: "5 Seasons",
        episodeCount: 42,
        episodeTitle: "Stranger Things",
        logoImage: {
          videoId: 80057281,
          url: "https://occ-0-3933-116.1.nflxso.net/dnm/api/v6/beuYL-MTCxPyt5oTOhVnWNGfZug/AAAABW24MI8VEhVtBFpH_x3AKG1mKl1FV12cmNBoxBrxF4gNilBrm7iFnJhT67hSo0aq6Mfw3BHz1Ai2yyjPVdzsIA17Q2yv_rtOQxUewzZVlndST4qE4kHosLO-_Wigj0ZEp3_NrGICxsLsCWFEr9gh7rzu5slVDzGOGRSbJ8IYxhMXjfHS4PMf.webp?r=347",
          type: "LOGO_BRANDED_HORIZONTAL",
          width: 625,
          height: 250,
          extension: "webp",
          size: "_LOGO_BRANDED_HORIZONTAL",
          imageKey:
            "LOGO_BRANDED_HORIZONTAL|25d10400-b6bb-11f0-b006-0affdb983e37:4a71f320-40b7-11f0-b0e1-0afffa5bd6e5|en",
        },
        backgroundImage: {
          videoId: "80057281",
          url: "https://occ-0-3933-116.1.nflxso.net/dnm/api/v6/9pS1daC2n6UGc3dUogvWIPMR_OU/AAAABfjWkIsbLBQd9mPJl65qjeCR80RYHPT_pWkapHi-AjHQKs-mF1APr2abph5k1S50CR8ecn-Uvfsi_EJjHRpzdH8JsEyfeyml1lUthBRF4D9l8njtxkC7NFRLGg.webp?r=b6b",
          width: 853,
          height: 480,
          image_key: "MERCH_STILL|dfa3e890-c9b5-11f0-8f55-12e5528d6511|en",
        },
      },
    },
    {
      availability: { isPlayable: true, unplayableCause: null },
      inRemindMeList: false,
      queue: { available: true, inQueue: false },
      summary: {
        type: "show",
        unifiedEntityId: "Video:80187302",
        id: 80187302,
        isOriginal: false,
        liveEvent: { hasLiveEvent: false },
      },
      episodeCount: 32,
      jawSummary: {
        trackIds: {
          videoId: 80187302,
          trackId_jaw: 14277281,
          trackId_jawEpisode: 14277283,
          trackId_jawTrailer: 14277282,
          trackId: 14277281,
        },
        tags: [
          { id: 100033, name: "Cerebral" },
          { id: 100055, name: "Suspenseful" },
        ],
        cast: [
          { id: 40080402, name: "Cho Seung-woo" },
          { id: 20036721, name: "Bae Doona" },
          { id: 30145635, name: "Jeon Hye-jin" },
          { id: 30167252, name: "Choi Mu-sung" },
          { id: 30129449, name: "Lee Jun-hyuk" },
          { id: 30174694, name: "Yoon Se-ah" },
          { id: 30141856, name: "Lee Kyung-yung" },
          { id: 40110818, name: "Yoo Jae-myung" },
          { id: 40110839, name: "Shin Hae-sun" },
        ],
        creators: [
          { id: 30047903, name: "Lee Su-yeon" },
          { id: 60177308, name: "Park Hyeon-seok" },
          { id: 40110941, name: "An Gil-ho" },
        ],
        directors: [],
        writers: [],
        genres: [
          { id: 11714, name: "TV Dramas" },
          { id: 81427756, name: "Korean" },
          { id: 26146, name: "Crime TV Shows" },
          { id: 89811, name: "TV Thrillers" },
        ],
        availability: { isPlayable: true, unplayableCause: null },
        contextualSynopsis: {
          text: "With the help of a gutsy female detective, a prosecutor who has lost the ability to feel empathy tackles a murder case amid political corruption.",
          evidenceKey: "synopsis|80187302_INFORMATIVE|en",
        },
        currentContextualSynopsis: {
          text: "As a teen, prosecutor Hwang Si-mok received surgical treatment for his abnormally developed brain, but the procedure left behind serious side effects.",
          evidenceKey: "web_synopsis|80187190_INFORMATIVE|en",
        },
        maturity: {
          rating: {
            value: "TV-MA",
            maturityDescription: "For Mature Audiences.",
            specificRatingReason: "violence, language, smoking",
            maturityLevel: 110,
            board: "US TV",
            boardId: 10,
            ratingId: 138,
            reasons: [
              {
                id: 7415,
                levelDescription: null,
                reasonDescription: "violence",
              },
              {
                id: 7426,
                levelDescription: null,
                reasonDescription: "language",
              },
              {
                id: 7430,
                levelDescription: null,
                reasonDescription: "smoking",
              },
            ],
          },
        },
        unifiedEntityId: "Video:80187302",
        id: 80187302,
        type: "show",
        isOriginal: false,
        liveEvent: {},
        mostLikedVideoId: 80187302,
        videoId: 80187302,
        requestId: "2a549fd8-0bd0-4388-a413-3a9b19ce9a03-167722651",
        userRatingRequestId: "2a549fd8-0bd0-4388-a413-3a9b19ce9a03-167722651",
        title: "Stranger",
        copyright: null,
        releaseYear: 2020,
        watched: false,
        hasAudioDescription: false,
        synopsis:
          "With the help of a gutsy female detective, a prosecutor who has lost the ability to feel empathy tackles a murder case amid political corruption.",
        synopsisRegular:
          "With the help of a gutsy female detective, a prosecutor who has lost the ability to feel empathy tackles a murder case amid political corruption.",
        hasSensitiveMetaData: false,
        delivery: {
          has3D: false,
          hasHD: true,
          hasUltraHD: false,
          hasHDR: false,
          hasDolbyVision: false,
          hasDolbyAtmos: false,
          has51Audio: false,
          quality: "HD",
          hasAudioAssistive: false,
          hasTextClosedCaptions: false,
          hasAudioSpatial: false,
        },
        titleMaturity: { level: 110 },
        broadcaster: { broadcasterName: null },
        trailerSummary: { length: 2 },
        supplementalMessageIcon: "REGULAR",
        videoMerch: {
          unifiedEntityId: "Video:81327345",
          videoId: 80187302,
          id: 81327345,
          start: 0,
          computeId: "browse|81327345|en-TR|_UPD_",
        },
        seasonAbbr: "S1",
        seasonCount: 2,
        numSeasonsLabel: "2 Seasons",
        episodeCount: 32,
        episodeTitle: "Stranger",
        logoImage: {
          videoId: 80187302,
          url: "https://occ-0-3933-116.1.nflxso.net/dnm/api/v6/beuYL-MTCxPyt5oTOhVnWNGfZug/AAAABdwoVHVwyzhx7HEi3C4a6iHz_PNSGMYKDtS6Mkz8YtrQxivOV4WbR8-vGuMYCKLCioq7VfZziX3JidrF0Q3MISidfHEZSASQf1JSqRzZ1ts.webp?r=20c",
          type: "LOGO_BRANDED_HORIZONTAL",
          width: 625,
          height: 250,
          extension: "webp",
          size: "_LOGO_BRANDED_HORIZONTAL",
          imageKey:
            "LOGO_BRANDED_HORIZONTAL|3cdbce80-ca64-11ea-b097-12aaad94477f|en",
        },
        backgroundImage: {
          videoId: 80187302,
          url: "https://occ-0-3933-116.1.nflxso.net/dnm/api/v6/E8vDc_W8CLv7-yMQu8KMEC7Rrr8/AAAABY_6Sn6IUSn0na-BoEN-ylvRShj0eZgAUS45CXiFC6hI4FXDvPTByB9z2Ey_4B868HfNF_7nhgYZjdMufnmZdZW5r7e72v39Uzrj.webp?r=c49",
          width: 848,
          height: 477,
          extension: "webp",
          size: 480,
          focalPoint: '{"x":0.4281,"y":0.3653}',
          imageKey: "StoryArt|4939a960-d30e-11ea-b4b5-0a7cbc25b839|en",
        },
      },
    },
    {
      availability: { isPlayable: true, unplayableCause: null },
      inRemindMeList: false,
      queue: { available: true, inQueue: false },
      summary: {
        type: "show",
        unifiedEntityId: "Video:80197912",
        id: 80197912,
        isOriginal: true,
        liveEvent: { hasLiveEvent: false },
      },
      episodeCount: 7,
      jawSummary: {
        trackIds: {
          videoId: 80197912,
          trackId_jaw: 14277281,
          trackId_jawEpisode: 14277283,
          trackId_jawTrailer: 14277282,
          trackId: 14277281,
        },
        tags: [{ id: 108911, name: "Ominous" }],
        cast: [
          { id: 30024241, name: "Jim Rash" },
          { id: 40079933, name: "Matt Duffer" },
          { id: 40085807, name: "Ross Duffer" },
          { id: 20030590, name: "Shawn Levy" },
          { id: 30074539, name: "David Harbour" },
          { id: 40080327, name: "Finn Wolfhard" },
          { id: 40080328, name: "Millie Bobby Brown" },
          { id: 40080425, name: "Gaten Matarazzo" },
          { id: 40080241, name: "Caleb McLaughlin" },
          { id: 30172803, name: "Natalia Dyer" },
          { id: 40080224, name: "Charlie Heaton" },
          { id: 40013337, name: "Noah Schnapp" },
          { id: 40084216, name: "Joe Keery" },
          { id: 40093263, name: "Dacre Montgomery" },
          { id: 40007740, name: "Sadie Sink" },
          { id: 77279, name: "Paul Reiser" },
          { id: 3553, name: "Sean Astin" },
          { id: 40170468, name: "Randy Havens" },
          { id: 30148014, name: "Brett Gelman" },
          { id: 40098896, name: "Linnea Berthelsen" },
        ],
        creators: [],
        directors: [],
        writers: [],
        genres: [
          { id: 3030851, name: "Talk Shows" },
          { id: 3300242, name: "Sci-Fi TV" },
          { id: 60951, name: "Teen TV Shows" },
        ],
        availability: { isPlayable: true, unplayableCause: null },
        contextualSynopsis: {
          text: 'Hear firsthand from "Stranger Things" creators as they discuss their influences and inspirations for the hit show with key cast members.',
          evidenceKey: "synopsis|687952161710702594|en|_UPD_",
        },
        currentContextualSynopsis: {
          text: "Millie Bobby Brown, Finn Wolfhard, Shawn Levy and the Duffer Brothers sit down to discuss new characters and the season's most important themes.",
          evidenceKey: "web_synopsis|80197831_INFORMATIVE|en",
        },
        maturity: {
          rating: {
            value: "TV-14",
            maturityDescription:
              "Parents strongly cautioned. May not be suitable for ages under 14.",
            specificRatingReason: "language, smoking",
            maturityLevel: 90,
            board: "US TV",
            boardId: 10,
            ratingId: 137,
            reasons: [
              {
                id: 7426,
                levelDescription: null,
                reasonDescription: "language",
              },
              {
                id: 7430,
                levelDescription: null,
                reasonDescription: "smoking",
              },
            ],
          },
        },
        unifiedEntityId: "Video:80197912",
        id: 80197912,
        type: "show",
        isOriginal: true,
        liveEvent: {},
        mostLikedVideoId: 80197912,
        videoId: 80197912,
        requestId: "2a549fd8-0bd0-4388-a413-3a9b19ce9a03-167722651",
        userRatingRequestId: "2a549fd8-0bd0-4388-a413-3a9b19ce9a03-167722651",
        title: "Beyond Stranger Things",
        copyright: null,
        releaseYear: 2017,
        watched: false,
        hasAudioDescription: false,
        synopsis:
          'Secrets from the "Stranger Things 2" universe are revealed as cast and guests discuss the latest episodes with host Jim Rash. Caution: spoilers ahead!',
        synopsisRegular:
          'Secrets from the "Stranger Things 2" universe are revealed as cast and guests discuss the latest episodes with host Jim Rash. Caution: spoilers ahead!',
        hasSensitiveMetaData: false,
        delivery: {
          has3D: false,
          hasHD: true,
          hasUltraHD: false,
          hasHDR: false,
          hasDolbyVision: false,
          hasDolbyAtmos: false,
          has51Audio: true,
          quality: "HD",
          hasAudioAssistive: false,
          hasTextClosedCaptions: true,
          hasAudioSpatial: false,
        },
        titleMaturity: { level: 90 },
        broadcaster: { broadcasterName: null },
        trailerSummary: { length: 1 },
        supplementalMessageIcon: "REGULAR",
        videoMerch: {
          unifiedEntityId: "Video:80986956",
          videoId: 80197912,
          id: 80986956,
          start: 960,
          computeId: "browse|80986956|en-TR|_DEF_",
        },
        seasonAbbr: "",
        seasonCount: 1,
        numSeasonsLabel: "7 Episodes",
        episodeCount: 7,
        episodeTitle: "Beyond Stranger Things",
        logoImage: {
          videoId: 80197912,
          url: "https://occ-0-3933-116.1.nflxso.net/dnm/api/v6/beuYL-MTCxPyt5oTOhVnWNGfZug/AAAABfniabP6ysHO2q5Ja-Ldq-NdAT-FZQ_rCG5UcKvw_tqTAiM1o-F1kIyESSqYzk8Gq1JkJUFFoIg7xW61wgI1-14bYYzsoVpKZzCI0SWRb1u4uFbSO2vAaB2Tjlh0dasK6XAS8TaDDq93I6ovzSPQp09wScGuCcg7DruTWqdXN5_e3Ob7Ngxt.webp?r=27c",
          type: "LOGO_BRANDED_HORIZONTAL",
          width: 625,
          height: 250,
          extension: "webp",
          size: "_LOGO_BRANDED_HORIZONTAL",
          imageKey:
            "LOGO_BRANDED_HORIZONTAL|181c7481-b7ae-11e7-95f0-126ca9e7c60c:4a71f320-40b7-11f0-b0e1-0afffa5bd6e5|en",
        },
        backgroundImage: {
          videoId: 80197912,
          url: "https://occ-0-3933-116.1.nflxso.net/dnm/api/v6/E8vDc_W8CLv7-yMQu8KMEC7Rrr8/AAAABSpC47RXb8ajqsu_nlQZvg5bVQqEAOeNJ3GiMl6j8oqjCvpoQFd7zxdnZBrc8hp2Xxt8DUL5i0X5yV9jYy1Rj1-RiWIyWfWB2h9z.webp?r=18b",
          width: 848,
          height: 477,
          extension: "webp",
          size: 480,
          focalPoint: '{"x":0.3461,"y":0.2736}',
          imageKey: "StoryArt|d17feba0-b7b3-11e7-abb3-0e239ab36c92|en",
        },
      },
    },
    {
      availability: { isPlayable: true, unplayableCause: null },
      inRemindMeList: false,
      queue: { available: true, inQueue: false },
      summary: {
        type: "show",
        unifiedEntityId: "Video:81001209",
        id: 81001209,
        isOriginal: true,
        liveEvent: { hasLiveEvent: false },
      },
      episodeCount: 8,
      jawSummary: {
        trackIds: {
          videoId: 81001209,
          trackId_jaw: 14277281,
          trackId_jawEpisode: 14277283,
          trackId_jawTrailer: 14277282,
          trackId: 14277281,
        },
        tags: [{ id: 100055, name: "Suspenseful" }],
        cast: [
          { id: 30005279, name: "Richard Armitage" },
          { id: 20057011, name: "Siobhan Finneran" },
          { id: 20019332, name: "Jennifer Saunders" },
          { id: 20031493, name: "Shaun Dooley" },
          { id: 30004908, name: "Paul Kaye" },
          { id: 20038207, name: "Dervla Kirwan" },
          { id: 40094616, name: "Kadiff Kirwan" },
          { id: 40009025, name: "Hannah John-Kamen" },
          { id: 20007926, name: "Anthony Head" },
          { id: 76701, name: "Stephen Rea" },
          { id: 50044841, name: "Jacob Dudman" },
          { id: 40197394, name: "Ella-Rae Smith" },
          { id: 60066159, name: "Brandon Fellows" },
          { id: 30202248, name: "Misha Handley" },
        ],
        creators: [{ id: 40096176, name: "Harlan Coben" }],
        directors: [],
        writers: [],
        genres: [
          { id: 11714, name: "TV Dramas" },
          { id: 81399656, name: "British" },
          { id: 1819174, name: "TV Shows Based on Books" },
          { id: 4366, name: "TV Mysteries" },
          { id: 26146, name: "Crime TV Shows" },
        ],
        availability: { isPlayable: true, unplayableCause: null },
        contextualSynopsis: {
          text: "In this thrilling mystery series, a shocking rumor about a man's wife sends him searching for the truth.",
          evidenceKey: "synopsis|964560706470281217|en|_UPD_",
        },
        currentContextualSynopsis: {
          text: "A stranger approaches Adam Price with a disturbing allegation about his wife, Corinne. Meanwhile, detectives Johanna and Wes take on a bizarre case.",
          evidenceKey: "web_synopsis|81019618_INFORMATIVE|en",
        },
        maturity: {
          rating: {
            value: "TV-MA",
            maturityDescription: "For Mature Audiences.",
            specificRatingReason: "language, smoking",
            maturityLevel: 110,
            board: "US TV",
            boardId: 10,
            ratingId: 138,
            reasons: [
              {
                id: 7426,
                levelDescription: null,
                reasonDescription: "language",
              },
              {
                id: 7430,
                levelDescription: null,
                reasonDescription: "smoking",
              },
            ],
          },
        },
        unifiedEntityId: "Video:81001209",
        id: 81001209,
        type: "show",
        isOriginal: true,
        liveEvent: {},
        mostLikedVideoId: 81001209,
        videoId: 81001209,
        requestId: "2a549fd8-0bd0-4388-a413-3a9b19ce9a03-167722651",
        userRatingRequestId: "2a549fd8-0bd0-4388-a413-3a9b19ce9a03-167722651",
        title: "The Stranger",
        copyright: null,
        releaseYear: 2020,
        watched: false,
        hasAudioDescription: true,
        synopsis:
          "When a stranger makes a shocking claim about his wife, Adam Price's life upends as he becomes entangled in a web of secrets in this thriller series.",
        synopsisRegular:
          "When a stranger makes a shocking claim about his wife, Adam Price's life upends as he becomes entangled in a web of secrets in this thriller series.",
        hasSensitiveMetaData: false,
        delivery: {
          has3D: false,
          hasHD: true,
          hasUltraHD: false,
          hasHDR: false,
          hasDolbyVision: false,
          hasDolbyAtmos: false,
          has51Audio: true,
          quality: "HD",
          hasAudioAssistive: true,
          hasTextClosedCaptions: true,
          hasAudioSpatial: false,
        },
        titleMaturity: { level: 110 },
        broadcaster: { broadcasterName: null },
        trailerSummary: { length: 1 },
        supplementalMessageIcon: "REGULAR",
        videoMerch: {
          unifiedEntityId: "Video:81572488",
          videoId: 81001209,
          id: 81572488,
          start: 0,
          computeId: "browse|81572488|en-TR|_UPD_",
        },
        seasonAbbr: "S1",
        seasonCount: 1,
        numSeasonsLabel: "Limited Series",
        episodeCount: 8,
        episodeTitle: "The Stranger",
        logoImage: {
          videoId: 81001209,
          url: "https://occ-0-3933-116.1.nflxso.net/dnm/api/v6/beuYL-MTCxPyt5oTOhVnWNGfZug/AAAABXt1vYyVAoXqcGStYQzmrXv1iEPbxv6mTejLyIfH8ET0VwMiA-SU7-OaAZYANwxdn6ac8H2yWnYNOG5NUx2Nxwq69oLOaLgE29SeNycae32c1g1YnHKdqUHvjdVLsgHbmpUGBtFylcA4bNwjnTBEUGn52U_VnKwCXKymTP8_ydJBJqVEiXvi.webp?r=780",
          type: "LOGO_BRANDED_HORIZONTAL",
          width: 625,
          height: 250,
          extension: "webp",
          size: "_LOGO_BRANDED_HORIZONTAL",
          imageKey:
            "LOGO_BRANDED_HORIZONTAL|86985b30-1dfb-11ea-ae33-1252a14bc99a:4a71f320-40b7-11f0-b0e1-0afffa5bd6e5|en",
        },
        backgroundImage: {
          videoId: 81001209,
          url: "https://occ-0-3933-116.1.nflxso.net/dnm/api/v6/E8vDc_W8CLv7-yMQu8KMEC7Rrr8/AAAABXneP-OhknKjp4JRMVxz543n44x7u_zd8Q0GxY11icgJ9s61IAZqif8DjOp9rCX3fBKiENzg5KesyxAarpKMEozLBtiV4Apl4jut.webp?r=5f9",
          width: 848,
          height: 477,
          extension: "webp",
          size: 480,
          focalPoint: '{"x":0.3794,"y":0.2579}',
          imageKey: "StoryArt|a00b5d90-31c1-11ea-9ff7-0ea8ab30c000|en",
        },
      },
    },
    {
      availability: {
        isPlayable: false,
        unplayableCause: "NOT_AVAILABLE_FOR_ED",
      },
      inRemindMeList: false,
      queue: { available: false, inQueue: false },
      summary: {
        type: "show",
        unifiedEntityId: "Video:81398721",
        id: 81398721,
        isOriginal: true,
        liveEvent: { hasLiveEvent: false },
      },
      episodeCount: 0,
      jawSummary: {
        trackIds: {
          videoId: 81398721,
          trackId_jaw: 14277281,
          trackId_jawEpisode: 14277283,
          trackId_jawTrailer: 14277282,
          trackId: 14277281,
        },
        tags: [
          { id: 104784, name: "Nostalgic" },
          { id: 100041, name: "Exciting" },
        ],
        cast: [
          { id: 70606545, name: "Brooklyn Davey Norstedt" },
          { id: 60216028, name: "Jolie Hoang-Rappaport" },
          { id: 60285391, name: "Luca Diaz" },
          { id: 60609874, name: "Elisha Williams" },
          { id: 70606546, name: "Braxton Quinney" },
          { id: 60208076, name: "Benjamin Plessala" },
          { id: 40099671, name: "Odessa A’zion" },
          { id: 30126286, name: "Brett Gipson" },
          { id: 30166853, name: "Jeremy Jordan" },
          { id: 160792, name: "Janeane Garofalo" },
          { id: 73362, name: "Lou Diamond Phillips" },
        ],
        creators: [],
        directors: [],
        writers: [],
        genres: [{ id: 451716, name: "Family Time TV" }],
        availability: {
          isPlayable: false,
          unplayableCause: "NOT_AVAILABLE_FOR_ED",
        },
        contextualSynopsis: {
          text: "Winter. Hawkins. 1985. Welcome back to a town crawling with secrets, where beloved heroes are facing fresh mysteries... and an all-new breed of strange.",
          evidenceKey: "synopsis|81398721_INFORMATIVE|en",
        },
        currentContextualSynopsis: {},
        maturity: {
          rating: {
            value: "TV-PG",
            maturityDescription: "Parental Guidance suggested",
            specificRatingReason: "violence, fear, language",
            maturityLevel: 70,
            board: "US TV",
            boardId: 10,
            ratingId: 136,
            reasons: [
              {
                id: 7415,
                levelDescription: null,
                reasonDescription: "violence",
              },
              { id: 7424, levelDescription: null, reasonDescription: "fear" },
              {
                id: 7426,
                levelDescription: null,
                reasonDescription: "language",
              },
            ],
          },
        },
        unifiedEntityId: "Video:81398721",
        id: 81398721,
        type: "show",
        isOriginal: true,
        liveEvent: {},
        mostLikedVideoId: 81398721,
        videoId: 81398721,
        requestId: "2a549fd8-0bd0-4388-a413-3a9b19ce9a03-167722651",
        userRatingRequestId: "2a549fd8-0bd0-4388-a413-3a9b19ce9a03-167722651",
        title: "Stranger Things: Tales From '85",
        copyright: null,
        releaseYear: 2026,
        watched: false,
        hasAudioDescription: true,
        synopsis:
          "Winter. Hawkins. 1985. Welcome back to a town crawling with secrets, where beloved heroes are facing fresh mysteries... and an all-new breed of strange.",
        synopsisRegular:
          "Winter. Hawkins. 1985. Welcome back to a town crawling with secrets, where beloved heroes are facing fresh mysteries... and an all-new breed of strange.",
        hasSensitiveMetaData: false,
        delivery: {
          has3D: false,
          hasHD: true,
          hasUltraHD: false,
          hasHDR: false,
          hasDolbyVision: false,
          hasDolbyAtmos: false,
          has51Audio: true,
          quality: "HD",
          hasAudioAssistive: true,
          hasTextClosedCaptions: true,
          hasAudioSpatial: false,
        },
        titleMaturity: { level: 70 },
        broadcaster: { broadcasterName: null },
        trailerSummary: { length: 2 },
        supplementalMessage: "A New Adventure Awaits: April 23",
        supplementalMessageIcon: "REGULAR",
        videoMerch: {
          unifiedEntityId: "Video:82648332",
          videoId: 81398721,
          id: 82648332,
          start: 0,
          computeId: "browse|82648332|en-TR|_DEF_",
        },
        logoImage: {
          videoId: 81398721,
          url: "https://occ-0-3933-116.1.nflxso.net/dnm/api/v6/beuYL-MTCxPyt5oTOhVnWNGfZug/AAAABb3c2TbNOiNDMwluspzHZW751fzkjH559QcpysX5zu6gdR6xSq96aR4_ZPWZZCyKeZRhyMULLHC1wVNaZ3Z5_Ow22dZwP1B2kpZ1pBsR2ENX15WT_KyisTwusN5VokTE4dfWh9GI_JJ4as7jhXnaInTKLlOW1YQDxzHpS44gS4eZGKVndHHQ.webp?r=612",
          type: "LOGO_BRANDED_HORIZONTAL",
          width: 625,
          height: 250,
          extension: "webp",
          size: "_LOGO_BRANDED_HORIZONTAL",
          imageKey:
            "LOGO_BRANDED_HORIZONTAL|3771d030-a622-11f0-903a-0affd247cb2b:4a71f320-40b7-11f0-b0e1-0afffa5bd6e5|en",
        },
        backgroundImage: {
          videoId: 81398721,
          url: "https://occ-0-3933-116.1.nflxso.net/dnm/api/v6/E8vDc_W8CLv7-yMQu8KMEC7Rrr8/AAAABT-RTlLpdT8InBd9UB6lTpDBsJK4axA54GBIn6DAjp_jcmvV2NN0pNXUrFDEiq2mNE-_sKPyNBVeT1p3Lthwx6WEq-d0I3ri9t8y.webp?r=1a5",
          width: 848,
          height: 477,
          extension: "webp",
          size: 480,
          focalPoint: '{"x":0.5018,"y":0.1759}',
          imageKey: "StoryArt|e3450ac0-19af-11f1-92c2-0e04c9986259|en",
        },
      },
    },
    {
      availability: { isPlayable: true, unplayableCause: null },
      inRemindMeList: false,
      queue: { available: true, inQueue: false },
      summary: {
        type: "movie",
        unifiedEntityId: "Video:81447229",
        id: 81447229,
        isOriginal: true,
        liveEvent: { hasLiveEvent: false },
      },
      jawSummary: {
        trackIds: {
          videoId: 81447229,
          trackId_jaw: 14277281,
          trackId_jawEpisode: 14277283,
          trackId_jawTrailer: 14277282,
          trackId: 14277281,
        },
        tags: [{ id: 100034, name: "Violent" }],
        cast: [
          { id: 60045169, name: "Joey Bada$$" },
          { id: 20040742, name: "Andrew Howard" },
          { id: 60356190, name: "Zaria" },
        ],
        creators: [],
        directors: [
          { id: 60029068, name: "Travon Free" },
          { id: 60012952, name: "Martin Desmond Roe" },
        ],
        writers: [{ id: 60029068, name: "Travon Free" }],
        genres: [
          { id: 5763, name: "Drama Movies" },
          { id: 3947, name: "Social Issue Dramas" },
        ],
        availability: { isPlayable: true, unplayableCause: null },
        contextualSynopsis: {
          text: "In this Oscar-winning short film, a man trying to get home to his dog becomes stuck in a time loop that forces him to relive a deadly run-in with a cop.",
          evidenceKey: "synopsis|81447229-DEFAULT-Narrative--en|en|_UPD_",
        },
        currentContextualSynopsis: {
          text: "In this Oscar-winning short film, a man trying to get home to his dog becomes stuck in a time loop that forces him to relive a deadly run-in with a cop.",
          evidenceKey: "synopsis|81447229-DEFAULT-Narrative--en|en|_UPD_",
        },
        maturity: {
          rating: {
            value: "TV-MA",
            maturityDescription: "For Mature Audiences.",
            specificRatingReason: "violence, language, smoking",
            maturityLevel: 110,
            board: "US TV",
            boardId: 10,
            ratingId: 138,
            reasons: [
              {
                id: 7415,
                levelDescription: null,
                reasonDescription: "violence",
              },
              {
                id: 7426,
                levelDescription: null,
                reasonDescription: "language",
              },
              {
                id: 7430,
                levelDescription: null,
                reasonDescription: "smoking",
              },
            ],
          },
        },
        unifiedEntityId: "Video:81447229",
        id: 81447229,
        type: "movie",
        isOriginal: true,
        liveEvent: {},
        mostLikedVideoId: 81447229,
        videoId: 81447229,
        requestId: "2a549fd8-0bd0-4388-a413-3a9b19ce9a03-167722651",
        userRatingRequestId: "2a549fd8-0bd0-4388-a413-3a9b19ce9a03-167722651",
        title: "Two Distant Strangers",
        copyright: null,
        releaseYear: 2021,
        watched: false,
        hasAudioDescription: true,
        synopsis:
          "In this Oscar-winning short film, a man trying to get home to his dog becomes stuck in a time loop that forces him to relive a deadly run-in with a cop.",
        synopsisRegular:
          "In this Oscar-winning short film, a man trying to get home to his dog becomes stuck in a time loop that forces him to relive a deadly run-in with a cop.",
        hasSensitiveMetaData: false,
        delivery: {
          has3D: false,
          hasHD: true,
          hasUltraHD: false,
          hasHDR: false,
          hasDolbyVision: false,
          hasDolbyAtmos: false,
          has51Audio: true,
          quality: "HD",
          hasAudioAssistive: true,
          hasTextClosedCaptions: true,
          hasAudioSpatial: false,
        },
        titleMaturity: { level: 110 },
        broadcaster: { broadcasterName: null },
        trailerSummary: { length: 1 },
        supplementalMessageIcon: "REGULAR",
        runtime: 1923,
        videoMerch: {
          unifiedEntityId: "Video:81450707",
          videoId: 81447229,
          id: 81450707,
          start: 20,
          computeId: "browse|81450707|en-TR|_DEF_",
        },
        logoImage: {
          videoId: 81447229,
          url: "https://occ-0-3933-116.1.nflxso.net/dnm/api/v6/beuYL-MTCxPyt5oTOhVnWNGfZug/AAAABRZ5sbA3MvqgFRX87sO0JBkpzz9OpdQz_ey1AbTWBqDuUz6OUTGcUtkDFsHZG-XcRkgKV8JeGVWWn282Axrh5TGY9NB5SJxvqVEtAwkYe2kYDk0McG5wpnrrgzWrM7DyT1rDex5MA2vo06S_dnjxt_hubLYn0Rir3HMqs9-1Chmij7XAa-Uf.webp?r=1e0",
          type: "LOGO_BRANDED_HORIZONTAL",
          width: 625,
          height: 250,
          extension: "webp",
          size: "_LOGO_BRANDED_HORIZONTAL",
          imageKey:
            "LOGO_BRANDED_HORIZONTAL|835f1830-fe9e-11ef-b19b-0e6c53716b1b:4a71f320-40b7-11f0-b0e1-0afffa5bd6e5|en",
        },
        backgroundImage: {
          videoId: 81447229,
          url: "https://occ-0-3933-116.1.nflxso.net/dnm/api/v6/E8vDc_W8CLv7-yMQu8KMEC7Rrr8/AAAABbKRAW80Y_DjqwgtsddphXsZASXZcyMKJTihsxjd3WelPfeCvpNuEQMIdQRDbqUX1VzVJubLShncAu6JxgZNq0syAYr5rm5i7X4J.webp?r=40d",
          width: 848,
          height: 477,
          extension: "webp",
          size: 480,
          focalPoint: '{"x":0.3839,"y":0.3505}',
          imageKey: "StoryArt|acde2f70-8dc8-11eb-aad4-0a7195518245|en",
        },
      },
    },
    {
      availability: { isPlayable: true, unplayableCause: null },
      inRemindMeList: false,
      queue: { available: true, inQueue: false },
      summary: {
        type: "movie",
        unifiedEntityId: "Video:81684720",
        id: 81684720,
        isOriginal: true,
        liveEvent: { hasLiveEvent: false },
      },
      jawSummary: {
        trackIds: {
          videoId: 81684720,
          trackId_jaw: 14277281,
          trackId_jawEpisode: 14277283,
          trackId_jawTrailer: 14277282,
          trackId: 14277281,
        },
        tags: [
          { id: 100047, name: "Inspiring" },
          { id: 100039, name: "Emotional" },
        ],
        cast: [],
        creators: [],
        directors: [{ id: 40204981, name: "Martina Radwan" }],
        writers: [],
        genres: [{ id: 2243108, name: "Documentary Films" }],
        availability: { isPlayable: true, unplayableCause: null },
        contextualSynopsis: {
          text: 'Millie Bobby Brown, Finn Wolfhard and other stars join the Duffer Brothers for a behind-the-scenes peek at how "Stranger Things" comes to life.',
          evidenceKey: "synopsis|2425945355262829642|en|_UPD_",
        },
        currentContextualSynopsis: {
          text: 'Millie Bobby Brown, Finn Wolfhard and other stars join the Duffer Brothers for a behind-the-scenes peek at how "Stranger Things" comes to life.',
          evidenceKey: "synopsis|2425945355262829642|en|_UPD_",
        },
        maturity: {
          rating: {
            value: "TV-14",
            maturityDescription:
              "Parents strongly cautioned. May not be suitable for ages under 14.",
            specificRatingReason: "language, gore, smoking",
            maturityLevel: 90,
            board: "US TV",
            boardId: 10,
            ratingId: 137,
            reasons: [
              {
                id: 7426,
                levelDescription: null,
                reasonDescription: "language",
              },
              { id: 7429, levelDescription: null, reasonDescription: "gore" },
              {
                id: 7430,
                levelDescription: null,
                reasonDescription: "smoking",
              },
            ],
          },
        },
        unifiedEntityId: "Video:81684720",
        id: 81684720,
        type: "movie",
        isOriginal: true,
        liveEvent: {},
        mostLikedVideoId: 81684720,
        videoId: 81684720,
        requestId: "2a549fd8-0bd0-4388-a413-3a9b19ce9a03-167722651",
        userRatingRequestId: "2a549fd8-0bd0-4388-a413-3a9b19ce9a03-167722651",
        title: "One Last Adventure: The Making of Stranger Things 5",
        copyright: null,
        releaseYear: 2026,
        watched: false,
        hasAudioDescription: true,
        synopsis:
          "An inside look at the years of effort and craft that went into the final installment of the Duffer Brothers' generation-defining series.",
        synopsisRegular:
          "An inside look at the years of effort and craft that went into the final installment of the Duffer Brothers' generation-defining series.",
        hasSensitiveMetaData: false,
        delivery: {
          has3D: false,
          hasHD: true,
          hasUltraHD: false,
          hasHDR: false,
          hasDolbyVision: false,
          hasDolbyAtmos: false,
          has51Audio: true,
          quality: "HD",
          hasAudioAssistive: true,
          hasTextClosedCaptions: true,
          hasAudioSpatial: false,
        },
        titleMaturity: { level: 90 },
        broadcaster: { broadcasterName: null },
        trailerSummary: { length: 1 },
        supplementalMessageIcon: "REGULAR",
        runtime: 7369,
        videoMerch: {
          unifiedEntityId: "Video:82632309",
          videoId: 81684720,
          id: 82632309,
          start: 0,
          computeId: "browse|82632309|en-TR|_UPD_",
        },
        logoImage: {
          videoId: 81684720,
          url: "https://occ-0-3933-116.1.nflxso.net/dnm/api/v6/beuYL-MTCxPyt5oTOhVnWNGfZug/AAAABQRViOMI5j6ndWeEj4ZGs9humCWITJzj3TCcQR_9IIT9hAsjvUH0t963BU2uni1GZObIOFMBUJd9hkGnMZOfqG8hAYTAbc6du6LTxH1s-uxw4GB2OSY1DDHnKpgMRvgdwlRfiGhQpn99GzOxndtLy1BQ2o5tu5T48qKa0wHKg99GM-TnNC12.webp?r=377",
          type: "LOGO_BRANDED_HORIZONTAL",
          width: 625,
          height: 250,
          extension: "webp",
          size: "_LOGO_BRANDED_HORIZONTAL",
          imageKey:
            "LOGO_BRANDED_HORIZONTAL|9ce474e0-c670-11f0-86e5-0ee544569163:4a71f320-40b7-11f0-b0e1-0afffa5bd6e5|en",
        },
        backgroundImage: {
          videoId: 81684720,
          url: "https://occ-0-3933-116.1.nflxso.net/dnm/api/v6/E8vDc_W8CLv7-yMQu8KMEC7Rrr8/AAAABR0euH0V9htexRl7TykXSt0ZG3Pth9pH_TySzrxAhjg8UqSkeVzUrKVBOL3ZZSidrGGTDnjop3xjfZHj6sOdHeyK2hPYgOxjCAEO.webp?r=58a",
          width: 848,
          height: 477,
          extension: "webp",
          size: 480,
          focalPoint: '{"x":0.4029,"y":0.4912}',
          imageKey: "StoryArt|640d3f50-dbc7-11f0-b62d-0e1735a010fb|en",
        },
      },
    },
  ],
  suggestions: [
    {
      summary: {
        unifiedEntityId:
          '{"score":"0.29225490771538676","queryRewrite":"{\\"count\\":4,\\"queries\\":[{\\"count\\":4,\\"query\\":\\"stranger\\"}]}","modelName":"rewrites-group-censored-decay-ed10-7474","source":"ClickModel","modelDate":"20260330","modelDagobahBatch":"1775047885539","isPrefixMatch":"true","displayHeader":"We don\'t have \\"${TITLE}\\" but you might like:","videoKind":"Standalone"}',
        id: null,
        type: "video",
        entityId: "Video:70170287",
        name: "Stranger Things",
        isTitleGroup: false,
        matchedlocale: null,
      },
    },
    {
      summary: {
        unifiedEntityId:
          '{"score":"0.04434765029071099","queryRewrite":"{\\"count\\":3,\\"queries\\":[{\\"count\\":3,\\"query\\":\\"stranger\\"}]}","modelName":"rewrites-group-censored-decay-ed10-7474","source":"ClickModel","modelDate":"20260330","modelDagobahBatch":"1775047885539","isPrefixMatch":"true","displayHeader":"We don\'t have \\"${TITLE}\\" but you might like:","videoKind":"Show"}',
        id: null,
        type: "video",
        entityId: "Video:81267632",
        name: "Strangers From Hell",
        isTitleGroup: false,
        matchedlocale: null,
      },
    },
    {
      summary: {
        unifiedEntityId:
          '{"score":"0.035915834213006294","queryRewrite":"{\\"count\\":24,\\"queries\\":[{\\"count\\":24,\\"query\\":\\"stranger\\"}]}","modelName":"rewrites-group-censored-decay-ed10-7474","source":"ClickModel","modelDate":"20260330","modelDagobahBatch":"1775047885539","isPrefixMatch":"true","displayHeader":"We don\'t have \\"${TITLE}\\" but you might like:","videoKind":"Standalone"}',
        id: null,
        type: "video",
        entityId: "Video:21879147",
        name: "The Strangers",
        isTitleGroup: false,
        matchedlocale: null,
      },
    },
    {
      summary: {
        unifiedEntityId:
          '{"score":"0.03335839894159357","queryRewrite":"{\\"count\\":3,\\"queries\\":[{\\"count\\":3,\\"query\\":\\"stranger\\"}]}","modelName":"rewrites-group-censored-decay-ed10-7474","source":"ClickModel","modelDate":"20260330","modelDagobahBatch":"1775047885539","isPrefixMatch":"true","displayHeader":"Titles in: ${TITLE}","enableTitleGroupTreatment":"true"}',
        id: null,
        type: "collection",
        entityId: "Collection:81233109",
        name: "Stranger Things Collection",
        isTitleGroup: true,
        matchedlocale: null,
      },
    },
    {
      summary: {
        unifiedEntityId:
          '{"score":"0.023452347945151403","queryRewrite":"{\\"count\\":2,\\"queries\\":[{\\"count\\":2,\\"query\\":\\"stranger\\"}]}","modelName":"rewrites-group-censored-decay-ed10-7474","source":"ClickModel","modelDate":"20260330","modelDagobahBatch":"1775047885539","isPrefixMatch":"true","displayHeader":"We don\'t have \\"${TITLE}\\" but you might like:","videoKind":"Standalone"}',
        id: null,
        type: "video",
        entityId: "Video:60037379",
        name: "Stranger Than Fiction",
        isTitleGroup: false,
        matchedlocale: null,
      },
    },
    {
      summary: {
        unifiedEntityId:
          '{"score":"0.021044970144077704","queryRewrite":"{\\"count\\":2,\\"queries\\":[{\\"count\\":2,\\"query\\":\\"stranger\\"}]}","modelName":"rewrites-group-censored-decay-ed10-7474","source":"ClickModel","modelDate":"20260330","modelDagobahBatch":"1775047885539","isPrefixMatch":"true","displayHeader":"We don\'t have \\"${TITLE}\\" but you might like:","videoKind":"Standalone"}',
        id: null,
        type: "video",
        entityId: "Video:81948262",
        name: "The Strangers: Chapter 2",
        isTitleGroup: false,
        matchedlocale: null,
      },
    },
    {
      summary: {
        unifiedEntityId:
          '{"score":"0.01972949146384094","queryRewrite":"{\\"count\\":1,\\"queries\\":[{\\"count\\":1,\\"query\\":\\"stranger\\"}]}","modelName":"rewrites-group-censored-decay-ed10-7474","source":"ClickModel","modelDate":"20260330","modelDagobahBatch":"1775047885539","isPrefixMatch":"true","displayHeader":"We don\'t have \\"${TITLE}\\" but you might like:","videoKind":"Standalone"}',
        id: null,
        type: "video",
        entityId: "Video:81775516",
        name: "The Strangers: Chapter 1",
        isTitleGroup: false,
        matchedlocale: null,
      },
    },
    {
      summary: {
        unifiedEntityId:
          '{"score":"0.015260109723930293","queryRewrite":"{\\"count\\":2,\\"queries\\":[{\\"count\\":2,\\"query\\":\\"stranger\\"}]}","modelName":"rewrites-group-censored-decay-ed10-7474","source":"ClickModel","modelDate":"20260330","modelDagobahBatch":"1775047885539","isPrefixMatch":"true","displayHeader":"We don\'t have \\"${TITLE}\\" but you might like:","videoKind":"Standalone"}',
        id: null,
        type: "video",
        entityId: "Video:70084187",
        name: "Strangers",
        isTitleGroup: false,
        matchedlocale: null,
      },
    },
    {
      summary: {
        unifiedEntityId:
          '{"score":"0.00833650036900502","queryRewrite":"{\\"count\\":2,\\"queries\\":[{\\"count\\":2,\\"query\\":\\"stranger\\"}]}","modelName":"rewrites-group-censored-decay-ed10-7474","source":"ClickModel","modelDate":"20260330","modelDagobahBatch":"1775047885539","isPrefixMatch":"true","displayHeader":"We don\'t have \\"${TITLE}\\" but you might like:","videoKind":"Standalone"}',
        id: null,
        type: "video",
        entityId: "Video:70285670",
        name: "Stranger by the Lake",
        isTitleGroup: false,
        matchedlocale: null,
      },
    },
    {
      summary: {
        unifiedEntityId:
          '{"score":"0.0081564476681273","queryRewrite":"{\\"count\\":2,\\"queries\\":[{\\"count\\":2,\\"query\\":\\"stranger\\"}]}","modelName":"rewrites-group-censored-decay-ed10-7474","source":"ClickModel","modelDate":"20260330","modelDagobahBatch":"1775047885539","isPrefixMatch":"true","displayHeader":"We don\'t have \\"${TITLE}\\" but you might like:","videoKind":"Standalone"}',
        id: null,
        type: "video",
        entityId: "Video:70271673",
        name: "Stranger in the House",
        isTitleGroup: false,
        matchedlocale: null,
      },
    },
  ],
};
export const DebounceSearch = (fn, delay = 500) => {
  let timer;

  const debounced = (...args) => {
    // cleared previous timer
    clearTimeout(timer);
    //   started new one timer
    timer = setTimeout(() => {
      // Calling function with latest function
      fn(...args);
    }, delay);
  };

  debounced.cancel = () => {
    clearTimeout(timer);
  };

  return debounced;
};
